### ISSUE TITLE
No releases

### ISSUE THREAD

**Issue by tuimz** [cybercog/laravel-notification-channel-rocket-chat#1]
Why are there no releases?

I'd prefer to use a tagged release instead of dev-master ;)

**Comment by antonkomarev** [comment]
You are right, I was raised a question on laravel-notification-channels to publish it on the list and was planned to publish it then, but they aren't added it.
I'm going to return to this package in near future, because I will require this functionality in next project.

In short: Will do it pretty soon. Thanks for pointing this out.

**Comment by tuimz** [comment]
Did they specify a reason? I am willing to put in some work to get this in the laravel-notifications-channels organisation on Github.

Edit: I was checking which notification channels they do actually support. Pretty sure this could replace your package: https://github.com/laravel-notification-channels/webhook

**Comment by antonkomarev** [comment]
https://github.com/laravel-notification-channels/new-channels/issues/6#issuecomment-283767862

**Comment by antonkomarev** [comment]
Oh... now I see that FAQ said I need to create PR with new channel proposal, but there are [a lot of PRs in a pending state](https://github.com/laravel-notification-channels/new-channels/pulls) without any response at this moment.

**Comment by tuimz** [comment]
Yeah, I have noticed that as well.
I think I will use the webhook channel as I mentioned before.

**Comment by antonkomarev** [comment]
Project moved: https://github.com/laravel-notification-channels/rocket-chat
